### ISSUE TITLE
Searching for ++ does not work

### ISSUE THREAD

**Issue by raine** [carlosgaldino/alfred-hoogle-workflow#3]
![screenshot 2014-10-17 11 34 35](https://cloud.githubusercontent.com/assets/11027/4676269/869018a8-55d8-11e4-8656-b4349db040fb.png)

**Comment by carlosgaldino** [comment]
@raine Thanks for the report. It should be fixed now. Please update your workflow with the new version that is on `master` and let me know if the error still occurs.

**Comment by raine** [comment]
Thanks. `++` works now.

I just came up with another one that should be escaped. `&&&` doesn't work.

**Comment by carlosgaldino** [comment]
@raine It should be fixed now.

I also fixed when searching using `<`, `>` and such.

Thanks again.
