### ISSUE TITLE
The workflow stopped working

### ISSUE THREAD

**Issue by raine** [carlosgaldino/alfred-hoogle-workflow#4]
Any idea? Maybe a change or temporary problem in hoogle API?

Either way, there probably should be a visible indication of such issue.

![hoogle](https://cloud.githubusercontent.com/assets/11027/4841364/cdf42acc-6019-11e4-84d9-6a74f84021b4.gif)

**Comment by carlosgaldino** [comment]
The API url has changed. A new version is on `master` and it should be fixed.

Thanks.
